routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SitesController;
use App\Http\Controllers\CommentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('/login');   
})->middleware(['auth'])->name('welcome');

Route::get('/logged-in', function () {
     return redirect('/');   
})->middleware(['auth'])->name('logged-in');

Route::get('/home', function () {
    return view('welcome');
})->middleware(['auth'])->name('home');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {

    // Sites
    Route::post('sites/data', [SitesController::class, 'data'])->name('sites.data');
    Route::resource('sites', SitesController::class);
    Route::get('/manage-sites/overview/{id}', [SitesController::class, 'siteOverview'])->name('siteOverview');

        // Active theme
        Route::get('/manage-sites/active_theme/{id}', [SitesController::class, 'activeTheme'])->name('activeTheme');

        // Plugins
        Route::get('/manage-sites/plugins/{id}', [SitesController::class, 'plugins'])->name('plugins');

        // Sites Users
        Route::post('/manage-sites/users/data/{id}', [SitesController::class, 'userIndexData'])->name('sites.user_index_data');
        Route::get('/manage-sites/users/{id}', [SitesController::class, 'userIndex'])->name('sites.user_index');
        Route::match(['GET', 'POST'], '/manage-sites/users/change-password/{site_id}/{user_id}/', [SitesController::class, 'changePassword'])->name('sites.change-password');
        Route::delete('/manage-sites/users/delete/{site_id}/{user_id}', [SitesController::class, 'deleteUser'])->name('sites.delete_user');
        

        // Sites Comments
        Route::post('/manage-sites/comments/data/{id}', [CommentController::class, 'data'])->name('sites.comments.data');
        Route::get('/manage-sites/comments/{id}', [CommentController::class, 'index'])->name('sites.comments.index');
        Route::delete('/manage-sites/empty-trash-comments/{id}', [CommentController::class, 'emptyTrashComments'])->name('sites.comments.empty-trash');
        Route::delete('/manage-sites/empty-spam-comments/{id}', [CommentController::class, 'deleteSpamComments'])->name('sites.comments.empty-spam');
        Route::delete('/manage-sites/trash-spam-comments/{id}', [CommentController::class, 'trashSpamComments'])->name('sites.comments.trash-spam');

    // User
    Route::match(['GET', 'POST'], 'users/{id}/change-password', [UserController::class, 'changePassword'])->name('users.change-password');
    Route::post('users/data', [UserController::class, 'data'])->name('users.data');
    Route::get('/user', [UserController::class, 'index'])->name('users.index');

});

resources/views/layouts/partials/backend_footer.blade.php
<!-- Footer -->
<footer id="page-footer" class="bg-body-light">
    <div class="content py-0">
        <div class="row font-size-sm">
            <div class="col-sm-6 order-sm-2 mb-1 mb-sm-0 text-center text-sm-right">
                Crafted with <i class="fa fa-heart text-danger"></i> by <a class="font-w600" href="https://www.vardaam.com/" target="_blank">Vardaam</a>
            </div>
            <div class="col-sm-6 order-sm-1 text-center text-sm-left">
                <a class="font-w600" href="https://www.vardaam.com/" target="_blank">Vardaam Web Solutions</a> &copy; <span data-toggle="year-copy"></span>
            </div>
        </div>
    </div>
</footer>
<!-- END Footer -->

resources/views/layouts/partials/backend_header.blade.php
<!-- Header -->
<header id="page-header">
    <!-- Header Content -->
    <div class="content-header">
        <!-- Left Section -->
        <div>
            <!-- Toggle Sidebar -->
            <!-- Layout API, functionality initialized in Template._uiApiLayout()-->
            <button type="button" class="btn btn-dual" data-toggle="layout" data-action="sidebar_toggle">
                <i class="fa fa-fw fa-bars"></i>
            </button>
            <!-- END Toggle Sidebar -->

            <!-- Open Search Section -->
            <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
            <button type="button" class="btn btn-dual" data-toggle="layout" data-action="header_search_on">
                <i class="fa fa-fw fa-search"></i> <span class="ml-1 d-none d-sm-inline-block">{{ __('global.search') }}</span>
            </button>
            <!-- END Open Search Section -->
        </div>
        <!-- END Left Section -->

        <!-- Right Section -->
        <div>
            <!-- User Dropdown -->
            <div class="dropdown d-inline-block">
                <button type="button" class="btn btn-dual" id="page-header-user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-fw fa-user d-sm-none"></i>
                    <span class="d-none d-sm-inline-block">Admin</span>
                    <i class="fa fa-fw fa-angle-down ml-1 d-none d-sm-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right p-0" aria-labelledby="page-header-user-dropdown">
                    <div class="p-2">
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <i class="far fa-fw fa-arrow-alt-circle-left mr-1"></i> Log Out
                        </a>
                        <form id="logout-form" style="display: none;" method="POST" action="{{ route('logout') }}">
                            @csrf
                        </form>
                    </div>
                </div>
            </div>
            <!-- END User Dropdown -->
            @if (session()->has('orig_user'))
            <a href="{{ route('users.switch_stop') }}" title="Switch to Original User"><i class="fa fa-power-off ml-3"></i></a>
            @endif
        </div>
       
        <!-- END Right Section -->
    </div>
    <!-- END Header Content -->

    <!-- Header Search -->
    <div id="page-header-search" class="overlay-header bg-primary">
        <div class="content-header">
            <form class="w-100" action="/dashboard" method="POST">
                @csrf
                <div class="input-group">
                    <div class="input-group-prepend">
                        <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
                        <button type="button" class="btn btn-primary" data-toggle="layout" data-action="header_search_off">
                            <i class="fa fa-fw fa-times-circle"></i>
                        </button>
                    </div>
                    <input type="text" class="form-control border-0" placeholder="Search or hit ESC.." id="page-header-search-input" name="page-header-search-input">
                </div>
            </form>
        </div>
    </div>
    <!-- END Header Search -->

    <!-- Header Loader -->
    <!-- Please check out the Loaders page under Components category to see examples of showing/hiding it -->
    <div id="page-header-loader" class="overlay-header bg-primary-darker">
        <div class="content-header">
            <div class="w-100 text-center">
                <i class="fa fa-fw fa-2x fa-sun fa-spin text-white"></i>
            </div>
        </div>
    </div>
    <!-- END Header Loader -->
</header>
<!-- END Header -->

resources/views/layouts/partials/backend_hero.blade.php
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">@yield('title')</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">Home</li>
                    <li class="breadcrumb-item active" aria-current="page">@yield('title')</li>
                </ol>
            </nav>
        </div>
   </div>
</div>

resources/views/layouts/partials/backend_sidebar.blade.php
@stack('styles')
<link rel="stylesheet" href="{{ asset('backoffice-asset/js/plugins/select2/css/select2.min.css') }}">

<!-- Sidebar -->
<nav id="sidebar" aria-label="Main Navigation">
    <!-- Side Header -->
    <div class="bg-header-dark">
        <div class="content-header bg-white-10">
            <!-- Logo -->
            <a class="font-w600 text-white tracking-wide" href="/">
                <span>
                    WORDPRESS MANAGER
                </span>
            </a>
            <!-- END Logo -->

            <!-- Options -->
            <div>
                <!-- Toggle Sidebar Style -->
                <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
                <!-- Class Toggle, functionality initialized in Helpers.coreToggleClass() -->
                <a class="js-class-toggle text-white-75" data-target="#sidebar-style-toggler" data-class="fa-toggle-off fa-toggle-on" onclick="Dashmix.layout('sidebar_style_toggle');Dashmix.layout('header_style_toggle');" href="javascript:void(0)">
                    <i class="fa fa-toggle-off" id="sidebar-style-toggler"></i>
                </a>
                <!-- END Toggle Sidebar Style -->

                <!-- Close Sidebar, Visible only on mobile screens -->
                <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
                <a class="d-lg-none text-white ml-2" data-toggle="layout" data-action="sidebar_close" href="javascript:void(0)">
                    <i class="fa fa-times-circle"></i>
                </a>
                <!-- END Close Sidebar -->
            </div>
            <!-- END Options -->
        </div>
    </div>
    <!-- END Side Header -->

    <!-- Sidebar Scrolling -->
    <div class="js-sidebar-scroll">
    <!-- Side Navigation -->
        <div class="content-side content-side-full">
            <ul class="nav-main">
                <li class="nav-main-item mt-4">  
                    <a class="nav-main-link" href="{{ route('home') }}">
                        <i class="nav-main-link-icon fa fa-location-arrow"></i>
                        <span class="nav-main-link-name">Dashboard</span>   
                    </a>
                </li>
                <li class="nav-main-item mt-3">  
                    <a class="nav-main-link" href="{{ route('users.index') }}">
                        <i class="nav-main-link-icon fa fa-users"></i>
                        <span class="nav-main-link-name">Users</span>   
                    </a>
                </li> 
                <li class="nav-main-item">
                    <a class="nav-main-link nav-main-link-submenu" data-toggle="submenu" aria-haspopup="true" aria-expanded="true" href="#">
                        <i class="nav-main-link-icon fa fa-sitemap"></i>
                        <span class="nav-main-link-name">Sites</span>
                    </a>
                    <ul class="nav-main-submenu">
                        <li class="nav-main-item">
                            <a class="nav-main-link" href="{{ route('sites.index') }}">
                                <span class="nav-main-link-name">Manage Sites</span>
                            </a>
                        </li>
                        <li class="nav-main-item">
                            <a class="nav-main-link" href="{{ route('sites.create') }}">
                                <span class="nav-main-link-name">Add New</span>
                            </a>
                        </li>
                    </ul>
                </li>            
            </ul>
        </div>
        <!-- END Side Navigation -->
    </div>
    <!-- END Sidebar Scrolling -->
</nav>